version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: webhook_pipeline_db
    restart: always
    environment:
      POSTGRES_DB: webhook_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webhook_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 10

  db_init:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webhook_pipeline
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: npm run db:init

  api:
    build: ./backend
    container_name: webhook_pipeline_api
    depends_on:
      postgres:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webhook_pipeline
      DB_USER: postgres
      DB_PASSWORD: postgres
      FAILURE_NOTIFICATION_URL: http://api:3000/subscriber-notification-service
    command: npm run start

  job_worker:
    build: ./backend
    container_name: webhook_pipeline_worker
    depends_on:
      postgres:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webhook_pipeline
      DB_USER: postgres
      DB_PASSWORD: postgres
      FAILURE_NOTIFICATION_URL: http://api:3000/subscriber-notification-service
    command: npm run start:worker

  delivery_worker:
    build: ./backend
    container_name: webhook_pipeline_delivery_worker
    depends_on:
      postgres:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webhook_pipeline
      DB_USER: postgres
      DB_PASSWORD: postgres
      FAILURE_NOTIFICATION_URL: http://api:3000/subscriber-notification-service
    command: npm run start:delivery-worker

  frontend:
    build: ./frontend
    container_name: webhook_pipeline_frontend
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  postgres_data: